"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import dateutil.parser
from apitizing_burgers import utils
from dataclasses_json import Undefined, dataclass_json
from datetime import datetime
from enum import Enum
from typing import List, Optional

class OrderStatus(str, Enum):
    r"""Status of the order"""
    CREATED = 'CREATED'
    PREPARING = 'PREPARING'
    READY = 'READY'
    DELIVERED = 'DELIVERED'
    CANCELLED = 'CANCELLED'


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class OrderOutput:
    r"""An order to be returned"""
    burger_ids: List[int] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('burger_ids') }})
    r"""List of burger ids in the order"""
    id: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The id of the order"""
    status: OrderStatus = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('status') }})
    table: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('table') }})
    r"""Table number for the order"""
    time: datetime = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('time'), 'encoder': utils.datetimeisoformat(False), 'decoder': dateutil.parser.isoparse }})
    r"""Time of the order"""
    note: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('note'), 'exclude': lambda f: f is None }})
    r"""Note for the order"""
    

