"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import orderoutput as components_orderoutput
from ...models.components import orderupdate as components_orderupdate
from typing import Optional


@dataclasses.dataclass
class UpdateOrderRequest:
    order_id: int = dataclasses.field(metadata={'path_param': { 'field_name': 'order_id', 'style': 'simple', 'explode': False }})
    order_update: components_orderupdate.OrderUpdate = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class UpdateOrderResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    order_output: Optional[components_orderoutput.OrderOutput] = dataclasses.field(default=None)
    r"""Successful Response"""
    

