"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import burgeroutput as components_burgeroutput
from ...models.components import burgerupdate as components_burgerupdate
from typing import Optional


@dataclasses.dataclass
class UpdateBurgerRequest:
    burger_id: int = dataclasses.field(metadata={'path_param': { 'field_name': 'burger_id', 'style': 'simple', 'explode': False }})
    burger_update: components_burgerupdate.BurgerUpdate = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class UpdateBurgerResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    burger_output: Optional[components_burgeroutput.BurgerOutput] = dataclasses.field(default=None)
    r"""Successful Response"""
    

